spring:
  datasource: 
    driver-class-name: "@datasource.driver@"
    url: "@datasource.url@"
    username: "@datasource.username@"
    password: "@datasource.password@"
server:
  port: "@server.port@"